name: hsamiplus
channels:
  - conda-forge
dependencies:
  - python >=3.12,<3.13
  # Docs
  - ipython >=8.5.0
  - nbsphinx >=0.9.5
  - sphinx >=7.1.0,<8.2
  - sphinx-codeautolink >=0.16.2
  - sphinx-copybutton
  - sphinx-intl
  - sphinx-rtd-theme >=1.0
  - typer >=0.16.0
